### ISSUE TITLE
Promise failed @ '_tickCallback nach JS.Contoller 2.0 Update

### ISSUE THREAD

**Issue by MarkSau** [iobroker-community-adapters/ioBroker.radar2#21]
Ich habe eben den JS-Controller 2.0 BETA installiert. Auch habe ich Redis für Objekte und Files aktiviert. Alles scheint soweit ok und läuft auch. Radar2 scheint auch zu tun, Anwesenheiten werden erkannt usw. Jedoch bekomme ich folgenden Fehler im Log:
`
2019-09-24 15:09:32.469  - [33mwarn[39m: radar2.0 (8556) Promise failed @ '_tickCallback in internal/process/next_tick.js @68:7' error: { TypeError: this[_0x5281(...)] is not a function at _0x244df9.(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:86122) at Object.checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:545:16) at Function.getObjectList (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:85955) at Promise (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@frankjoke/myadapter/myAdapter.js:828:111) at new Promise (<anonymous>) at Function.getObjectList (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@frankjoke/myadapter/myAdapter.js:828:20) at A.isLinuxApp.then.then.then.catch.then.then.then (/opt/iobroker/node_modules/iobroker.radar2/radar2.js:607:31) at process._tickCallback (internal/process/next_tick.js:68:7) [stack]: 'TypeError: this[_0x5281(...)] is not a function\n    at _0x244df9.(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:86122)\n    at Object.checkObjectRights (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsUtils.js:545:16)\n    at Function.getObjectList (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:17:85955)\n    at Promise (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@frankjoke/myadapter/myAdapter.js:828:111)\n    at new Promise (<anonymous>)\n    at Function.getObjectList (/opt/iobroker/node_modules/iobroker.radar2/node_modules/@frankjoke/myadapter/myAdapter.js:828:20)\n    at A.isLinuxApp.then.then.then.catch.then.then.then (/opt/iobroker/node_modules/iobroker.radar2/radar2.js:607:31)\n    at process._tickCallback (internal/process/next_tick.js:68:7)', [message]: 'this[_0x5281(...)] is not a function' }`

**Comment by Apollon77** [comment]
I have send MarkSau some details to get a more detailed errormessage ... then I can also check in the new js-controller objects lib ... maybe it is mainly there ,...

**Comment by Apollon77** [comment]
@frankjoke I analyzed it and I have no idea, beside that https://github.com/frankjoke/myAdapter/blob/18aa77cd2c98798c98fe711e60261cee28f60617/myAdapter.js#L824 could be the case.

In controller 1.5 the "objects.getObjectList" method was implemented "all in that method" and were kind of javascript functions. Now the whole Objects/StatesDBs are ES6 classes and also uses "this" to call other methods from this instance ... and here it breaks. the "ObjectsList" methjod calls "this._objectList" after doing right checks for the real logic and this fails.

In general it is _not_ best practice to access objects methods directly, but I also know that this was needed in js-controller <2.0 :-(

So from my current point of view: please check that your promise wrapper also correctly supports ES6 classes because elso all your adapters will get problems with js.controller because the call structure above (do rights checks and delegate logic to a second method) is now common.

**Comment by Apollon77** [comment]
@frankjoke One fix could be to repace "function()" by () => on your side so the the "this" context is not altered unexpectedly

**Comment by Apollon77** [comment]
No last idea did not worked out ... It feels like it would be needed to "bind" the returned function to the class content. Therefor you would need a new method to bind "classcontext "stuff ... But not tried so far, just idea

**Comment by MarkSau** [comment]
I've installed the same version 1.2.0 of the Github over it. Now I see the error nomore. its very strange

but another:

(869) No geo location data found configured in admin to calculate UWZ AREA ID or ID not valid!

Should I open a new issue for this?

**Comment by Apollon77** [comment]
I have released a fork of this package at @apollon/frankjoke-myadater as 1.2.5 to npm AND also published in coordination with @GermanBluefox a 1.0.8 of iobroker.radar2 which is using this lib.
This can be superceeded by @frankjoke at any time, but with this we can offer ioBroker users a version of radar2 which is compatible to js-controller 2.0.

Issue stays open

**Comment by Apollon77** [comment]
The 1.0.8 is based on https://github.com/frankjoke/ioBroker.radar2/commit/53063c7c50102a1186e02dd81b93712ca5189df8
